# Generated by Django 2.2 on 2023-11-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
