# Generated by Django 2.2 on 2023-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231108_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linked_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='for eg. 7859499938', max_length=10, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your updated resume.', null=True, upload_to='project_file/'),
        ),
    ]
