# Generated by Django 2.2 on 2021-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pic/'),
        ),
    ]
