# Generated by Django 2.2 on 2024-01-23 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=100)),
                ('position', models.CharField(choices=[('1', 'Position - 1'), ('2', 'Position - 2'), ('3', 'Position - 3'), ('4', 'Position - 4'), ('5', 'Position - 5'), ('6', 'Position - 6'), ('7', 'Position - 7'), ('8', 'Position - 8'), ('9', 'Position - 9')], help_text='Project position in Home page i.e. (1-9)', max_length=1, verbose_name='Project position')),
                ('description', models.CharField(help_text='Description of that project', max_length=700)),
                ('tools', models.CharField(blank=True, help_text='Tools used for creating this project (Separate tool by comma and not more than 5 tools)', max_length=700, null=True)),
                ('isometric_image', models.ImageField(help_text='Upload isometric view of the model.', upload_to='images/')),
                ('isometric_image_title', models.CharField(blank=True, help_text='(OPTIONAL) Title of projects images', max_length=50, null=True)),
                ('front_image', models.ImageField(help_text='Upload front view of the model.', upload_to='images/')),
                ('front_image_title', models.CharField(blank=True, help_text='(OPTIONAL) Title of projects images', max_length=50, null=True)),
                ('side_image', models.ImageField(blank=True, help_text='(OPTIONAL) Upload side view of the model.', null=True, upload_to='images/')),
                ('side_image_title', models.CharField(blank=True, help_text='(OPTIONAL) Title of projects images', max_length=50, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My-Project',
                'verbose_name_plural': 'My-Projects',
            },
        ),
    ]
