# Generated by Django 2.2 on 2021-01-05 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the projects', max_length=100)),
                ('description', models.CharField(help_text='Description of that projects', max_length=500)),
                ('isometric_image', models.ImageField(help_text='Upload isometric view of the model.', upload_to='images/')),
                ('front_image', models.ImageField(help_text='Upload front view of the model.', upload_to='images/')),
                ('side_image', models.ImageField(help_text='Upload side view of the model.', upload_to='images/')),
                ('top_image', models.ImageField(blank=True, help_text='Upload top view of the model.(OPTIONAL)', null=True, upload_to='images/')),
                ('bottom_image', models.ImageField(blank=True, help_text='Upload bottom view of the model.(OPTIONAL)', null=True, upload_to='images/')),
                ('project_file', models.FileField(help_text='Upload Your Project file.', upload_to='project_file/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
