# Generated by Django 2.2 on 2023-11-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'My-Project', 'verbose_name_plural': 'My-Projects'},
        ),
    ]
