# Generated by Django 2.2 on 2021-01-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='bottom_image',
            field=models.ImageField(blank=True, help_text='Upload bottom image of the model.', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='top_image',
            field=models.ImageField(blank=True, help_text='Upload top image of the model.', null=True, upload_to='images/'),
        ),
    ]
