# Generated by Django 2.2 on 2023-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20231108_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(help_text='Description of that projects', max_length=600),
        ),
    ]
