# Generated by Django 2.2 on 2023-11-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20231109_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_file',
            field=models.FileField(blank=True, help_text='Upload Your Project file.', null=True, upload_to='project_file/'),
        ),
    ]
