# Generated by Django 2.2 on 2023-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20231109_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_file',
            field=models.FileField(blank=True, help_text='(OPTIONAL) Upload Your Project file.', null=True, upload_to='project_file/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_file_link',
            field=models.URLField(blank=True, help_text='(OPTIONAL) For eg. github link', max_length=100, null=True),
        ),
    ]
